DMR-is/dmr.is

apps/official-journal-api/src/app/journal.controller.ts, apps/official-journal-api/src/app/journal.service.mock.ts, apps/official-journal-api/src/dto/adverts/journal-advert.dto.ts, apps/official-journal-api/src/dto/application/journal-postapplication-body.dto.ts, apps/official-journal-api/src/dto/application/journal-postapplication-response.dto.ts, apps/official-journal-api/src/dto/journal-constants.dto.ts, package.json, yarn.lock
- New submit endpoint with according models.
=> feat: Application submission

apps/official-journal-api/src/app/statistics/statistics.controller.spec.ts, apps/official-journal-api/src/app/statistics/statistics.controller.ts, apps/official-journal-api/src/app/statistics/statistics.service.interface.ts, apps/official-journal-api/src/app/statistics/statistics.service.mock.ts, apps/official-journal-api/src/app/statistics/statistics.service.spec.ts, apps/official-journal-api/src/app/statistics/statistics.service.ts, apps/official-journal-api/src/dto/statistics/statistics-overview-dto.ts, apps/official-journal-api/src/dto/statistics/statistics-overview-query.dto.ts
- added new endpoint to controller
- added method to service
- added tests for controller and service
- created models for query and response
=> feat(statistics): Overview endpoint 

apps/official-journal-api/src/app/statistics/statistics.controller.ts, apps/official-journal-api/src/app/statistics/statistics.service.interface.ts, apps/official-journal-api/src/app/statistics/statistics.service.mock.ts, apps/official-journal-api/src/app/statistics/statistics.service.ts, apps/official-journal-api/src/dto/statistics/statistics-overview-dto.ts
- Fixing openapi return type of route in statistics controller
- changing name of model to more appropriate value
=> fix(api): Fixing statistics controller return type

.prettierignore, apps/hello-world-api/project.json, apps/hello-world/app/page.tsx, apps/hello-world/clientConfig.json, apps/hello-world/lib/api.ts, apps/hello-world/lib/buildFetch.ts, apps/hello-world/lib/createEnhancedFetch.ts, apps/hello-world/lib/nodeFetch.ts, apps/hello-world/lib/types.ts, apps/hello-world/project.json, apps/official-journal-api/project.json, apps/official-journal-api/src/dto/case/case-comment-task.dto.ts, apps/official-journal-api/src/dto/case/case.dto.ts, libs/apm/project.json, nx.json, package.json, yarn.lock
- added openapi dependency
- added script to generate clientConfig
- added script to generate client
- fixed broken api documentation
=> feat(web): Generated client in web app

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-admin-api/src/app/case/case.service.mock.ts, apps/official-journal-web/project.json, apps/official-journal-web/src/components/filter-group/FilterGroup.tsx, apps/official-journal-web/src/context/filterContext.tsx, apps/official-journal-web/src/lib/utils.tsx, apps/official-journal-web/src/screens/CaseOverview.tsx, apps/official-journal-web/src/screens/CaseProcessingOverview.tsx, apps/official-journal-web/src/screens/CasePublishingOverview.tsx, libs/shared/dto/src/lib/cases/get-cases-query.dto.ts, package.json, scripts/codegen.js, scripts/utils.js
- added case filtering to pages
- added codegen script
=> feat(web): Adding advanced filtering

apps/official-journal-web/clientConfig.json, apps/official-journal-web/project.json, apps/official-journal-web/src/components/case-publishing-tab/CasePublishingTab.tsx, apps/official-journal-web/src/components/tables/CaseTableSelectedCases.tsx, apps/official-journal-web/src/screens/CasePublishingOverview.tsx, scripts/codegen.js
=> fix(infra): Fix codegen and deployment

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-admin-api/src/app/case/case.service.interface.ts, apps/official-journal-admin-api/src/app/case/case.service.mock.ts, apps/official-journal-admin-api/src/app/case/case.service.ts, apps/official-journal-web/src/lib/api/createClient.ts, libs/shared/dto/src/lib/cases/post-publish-body.dto.ts, libs/shared/dto/src/lib/index.ts
- cases publish endpoint
- update env variable
=> feat(api): Cases publish 

apps/official-journal-admin-api/src/app/case/case.service.mock.ts, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/tables/CaseTable.tsx, apps/official-journal-web/src/components/tables/CaseTableInProgress.tsx, apps/official-journal-web/src/components/tables/CaseTableInReview.tsx, apps/official-journal-web/src/components/tables/CaseTableOverview.tsx, apps/official-journal-web/src/components/tables/CaseTableReady.tsx, apps/official-journal-web/src/components/tables/CaseTableSubmitted.tsx, apps/official-journal-web/src/hooks/useQueryParams.ts, apps/official-journal-web/src/screens/CaseOverview.tsx, apps/official-journal-web/src/screens/CaseProcessingOverview.tsx, libs/shared/dto/src/lib/cases/get-cases-query.dto.ts, libs/shared/utils/src/lib/utils.ts
- table improvements
- pagination
=> feat(web): Pagination and table ui improvements

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-admin-api/src/app/case/case.module.ts, apps/official-journal-admin-api/src/app/statistics/statistics.module.ts, libs/shared/modules/src/auth/auth.module.ts, libs/shared/modules/src/auth/auth.service.interface.ts, libs/shared/modules/src/auth/auth.service.ts, libs/shared/modules/src/index.ts, libs/shared/modules/src/journal/journal.module.ts, libs/shared/modules/src/journal/journal.service.mock.ts, libs/shared/modules/src/journal/journal.service.ts, libs/shared/modules/tsconfig.json
- new auth module that handles authentication with island-is ids
- using the auth service in journal service
=> feat(api): Auth module

apps/official-journal-admin-api/src/app/statistics/statistics.controller.spec.ts, apps/official-journal-admin-api/src/app/statistics/statistics.service.spec.ts, apps/official-journal-api/src/app/app.spec.ts, libs/shared/dto/src/lib/application/application-answers.dto.ts, libs/shared/dto/src/lib/application/application-events.dto.ts, libs/shared/dto/src/lib/application/application.dto.ts, libs/shared/dto/src/lib/index.ts, libs/shared/modules/src/application/application.module.ts, libs/shared/modules/src/application/application.service.interface.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/journal/journal.controller.ts, libs/shared/modules/src/journal/journal.module.ts, libs/shared/modules/src/journal/journal.service.interface.ts, libs/shared/modules/src/journal/journal.service.mock.ts, libs/shared/modules/src/journal/journal.service.ts
Moved logic related to the application system to its own module
=> feat(api): Application module

apps/official-journal-admin-api/src/app/case/case.service.ts, apps/official-journal-admin-api/src/app/statistics/statistics.service.ts, libs/shared/modules/src/journal/journal.service.ts
- copied logic to main service to enable commincations to dev
=> chore(api): Moving logic to main service

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-admin-api/src/app/case/case.service.interface.ts, apps/official-journal-admin-api/src/app/case/case.service.mock.ts, apps/official-journal-admin-api/src/app/case/case.service.ts, apps/official-journal-admin-api/src/lib/utils.ts, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/comments/Comments.tsx, apps/official-journal-web/src/components/comments/messages.ts, apps/official-journal-web/src/pages/api/addComment.ts, apps/official-journal-web/src/pages/api/comments/delete.ts, apps/official-journal-web/src/pages/api/comments/post.ts, apps/official-journal-web/src/screens/CaseProcessingDetail.tsx, libs/mocks/src/lib/case.mock.ts, libs/shared/dto/src/lib/case-comments/case-comment-constants.ts, libs/shared/dto/src/lib/case-comments/case-comment.dto.ts, libs/shared/dto/src/lib/case-comments/get-case-comment-query.dto.ts, libs/shared/dto/src/lib/case-comments/post-case-comment.dto.ts, libs/shared/dto/src/lib/cases/case-constants.ts, libs/shared/dto/src/lib/cases/case.dto.ts, libs/shared/dto/src/lib/index.ts, package.json, yarn.lock
- case controller endpoints
- case comments api routes
=> feat(api, web): Case comments

apps/official-journal-admin-api/src/app/case/case.service.ts, libs/shared/dto/src/lib/cases/get-cases-query.dto.ts
- added application id to search params
=> feat(api): Add application id to case search parameters

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/case-publishing-list/CasePublishingList.tsx, apps/official-journal-web/src/components/case-publishing-tab/CasePublishingTab.tsx, apps/official-journal-web/src/components/tables/CasePublishingTable.tsx, apps/official-journal-web/src/components/tables/CaseTable.tsx, apps/official-journal-web/src/components/tables/CaseTableInProgress.tsx, apps/official-journal-web/src/components/tables/CaseTableInReview.tsx, apps/official-journal-web/src/components/tables/CaseTableOverview.tsx, apps/official-journal-web/src/components/tables/CaseTableReady.tsx, apps/official-journal-web/src/components/tables/CaseTableSelectedCases.tsx, apps/official-journal-web/src/components/tables/CaseTableSubmitted.tsx, apps/official-journal-web/src/components/tables/types.ts, apps/official-journal-web/src/screens/CaseProcessingOverview.tsx, apps/official-journal-web/src/screens/CasePublishingOverview.tsx, libs/mocks/src/lib/case.mock.ts, libs/shared/dto/src/lib/application/application-answers.dto.ts, libs/shared/dto/src/lib/cases/case-history.dto.ts, libs/shared/dto/src/lib/cases/case-with-application.dto.ts, libs/shared/dto/src/lib/cases/get-cases-with-application-response.dto.ts, libs/shared/dto/src/lib/index.ts, libs/shared/modules/src/case/case.service.interface.ts, libs/shared/modules/src/case/case.service.mock.ts, libs/shared/modules/src/case/case.service.ts
- switched out case to new case with application
- addded few methods and routes to controllers
=> fix(web): Using CaseWithApplication dto instead of Case

apps/official-journal-api/src/app/journal/journal.module.ts
=> fix(build): Fixing build 

libs/shared/sequelize/src/lib/sequelizeConfig.service.ts
- removed console.log that logged sensitive information
=> fix(db): Remove console logs

apps/official-journal-api/src/app/journal/journal.controller.spec.ts, apps/official-journal-api/src/app/journal/journal.controller.ts
- Fixed return values in journal controller to match swagger documentation
=> fix(api): Offiical journal api journal controller return types

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-api/seeders/initial-seed-official-journal.js, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/case-publishing-list/CasePublishingList.tsx, apps/official-journal-web/src/components/case-publishing-tab/CasePublishingTab.tsx, apps/official-journal-web/src/components/comments/Comments.tsx, apps/official-journal-web/src/components/form-steps/StepGrunnvinnsla.tsx, apps/official-journal-web/src/components/form-steps/StepInnsending.tsx, apps/official-journal-web/src/components/form-steps/StepTilbuid.tsx, apps/official-journal-web/src/components/form-steps/StepYfirlestur.tsx, apps/official-journal-web/src/components/tables/CasePublishingTable.tsx, apps/official-journal-web/src/components/tables/CaseTable.tsx, apps/official-journal-web/src/components/tables/CaseTableInProgress.tsx, apps/official-journal-web/src/components/tables/CaseTableInReview.tsx, apps/official-journal-web/src/components/tables/CaseTableOverview.tsx, apps/official-journal-web/src/components/tables/CaseTableReady.tsx, apps/official-journal-web/src/components/tables/CaseTableSelectedCases.tsx, apps/official-journal-web/src/components/tables/types.ts, apps/official-journal-web/src/lib/utils.tsx, apps/official-journal-web/src/pages/api/comments/delete.ts, apps/official-journal-web/src/pages/api/comments/post.ts, apps/official-journal-web/src/screens/CaseProcessingDetail.tsx, apps/official-journal-web/src/screens/CasePublishingOverview.tsx, libs/shared/dto/src/lib/cases/case-with-advert.dto.ts, libs/shared/dto/src/lib/cases/get-case-response.dto.ts, libs/shared/dto/src/lib/index.ts, libs/shared/modules/src/pdf/pdf.service.ts, libs/shared/modules/src/utility/utility.service.ts
- Updated types and fixed build errors
=> fix(web): Fixing build errors on web

apps/official-journal-api/src/app/journal/journal.controller.ts, apps/official-journal-web/clientConfig.json, libs/shared/dto/src/lib/cases/case-with-advert.dto.ts, libs/shared/modules/src/journal/journal.service.ts, libs/shared/modules/src/utility/utility.service.ts
- Improved error logging in journal service
=> fix(api): Improved logging

apps/official-journal-application-api/src/app/application/application.controller.ts, libs/shared/dto/src/lib/application/get-application-response.dto.ts, libs/shared/dto/src/lib/index.ts, libs/shared/modules/src/application/application.service.interface.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/utility/utility.service.ts
- Updated getApplication error handling and swagger documentation
=> fix(api): Improved error handling and documentation in getApplication

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-application-api/src/app/application/application.controller.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/auth/auth.service.ts, libs/shared/modules/src/case/case.service.interface.ts, libs/shared/modules/src/case/case.service.mock.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/pdf/pdf.service.ts, libs/shared/modules/src/utility/utility.service.interface.ts, libs/shared/modules/src/utility/utility.service.ts
- Improved error logging in case and application service
=> fix(api): More error logging improvements

libs/shared/modules/src/case/case.service.ts
- Added `requestedPublicationDate` and `advertTitle` to the create case model
=> fix(api): Creat case add properties

libs/shared/modules/src/case/case.service.ts
- Changed passing of whole department to only department id
=> fix(api): Create method

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-admin-api/src/app/case/case.module.ts, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/case-filters/CaseFilters.tsx, apps/official-journal-web/src/components/filter-group/FilterGroup.tsx, apps/official-journal-web/src/components/form-steps/StepGrunnvinnsla.tsx, apps/official-journal-web/src/lib/constants.ts, apps/official-journal-web/src/screens/CaseProcessingDetail.tsx, libs/shared/dto/src/lib/advert-types/get-adverttypes-query.dto.ts, libs/shared/modules/src/helpers/mappers/index.ts, libs/shared/modules/src/helpers/mappers/journal/index.ts, libs/shared/modules/src/helpers/mappers/journal/types-parameters.mapper.ts, libs/shared/modules/src/journal/journal.service.ts
- Adding correct values to input fields in case processing
- Adding filtering to advert types
=> fix(web): Updating UI before demo

apps/official-journal-web/src/lib/constants.ts
- Added back accidental removed CaseDepartmentsTabs
=> fix(web): Fix web deployment

libs/shared/modules/src/journal/journal.service.ts
=> feat(advert): Update advert params in get adverts

apps/official-journal-api/src/app/journal/journal.controller.ts, libs/shared/dto/src/lib/adverts/advert.dto.ts, libs/shared/modules/src/journal/journal.service.ts
=> fix(advert): Duplicate param error.

apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/attachments/Attachments.tsx, apps/official-journal-web/src/components/form-steps/StepInnsending.tsx, apps/official-journal-web/src/screens/CaseProcessingDetail.tsx, libs/shared/constants/src/lib/constants.ts, libs/shared/dto/src/lib/application/application-answers.dto.ts, libs/shared/dto/src/lib/application/application.dto.ts, libs/shared/dto/src/lib/cases/case-with-advert.dto.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/helpers/migrations/advert/advert-migrate.ts, libs/shared/modules/src/utility/utility.service.ts
- Added attachments to the advert dto
- updated web ui
=> feat(api): Adding attachments to advert

apps/official-journal-api/src/app/journal/journal.controller.ts, libs/shared/dto/src/lib/adverts/get-adverts-query.dto.ts, libs/shared/dto/src/lib/categories/get-categories-query.dto.ts, libs/shared/dto/src/lib/departments/get-departments-query.dto.ts, libs/shared/dto/src/lib/institutions/get-institutions-query.dto.ts, libs/shared/dto/src/lib/main-categories/get-maincategories-query.dto.ts, libs/shared/modules/src/journal/journal.service.ts
- added pageSize parameter to methods using paging
- added logging to every method in the service
- added endpoint in journal controller for single type
=> fix(api): Improve journal service

libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/journal/journal.service.ts, libs/shared/modules/src/lib/utils.ts, libs/shared/modules/src/utility/utility.service.ts, libs/shared/utils/src/lib/utils.ts
- improved error messages
- added generic bad request error handler
- removed noisy promise resolve
- added temp logging to getTypes method for debugging
=> fix(api): Improving error handling in journal service

libs/shared/utils/src/lib/utils.ts
- casting number string to number for correct comparison
=> fix(api): Pagination receving strings not number

libs/shared/modules/src/journal/journal.service.ts, libs/shared/utils/src/lib/utils.ts
- Removed where params from getTypes
- Fixed page out of range exception in generatePagination
=> fix(api): Removing where params from getTypes

libs/shared/utils/src/lib/utils.ts
- fixed wrong check on page vs total pages
=> fix(api): Pagination total page check

libs/shared/modules/src/decorators/audit.decorator.ts, libs/shared/modules/src/decorators/handle-exception.decorator.ts, libs/shared/modules/src/journal/journal.service.ts
- New `Audit` decorator that logs out the method that was called
- New `HandleException` decorator that wraps the function with try catch then return the already used `handleException` function
=> feat(api): Audit and exception decorators

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/lib/constants.ts, apps/official-journal-web/src/pages/api/case/assign.ts, apps/official-journal-web/src/pages/api/case/publish.ts, apps/official-journal-web/src/screens/CaseProcessingDetail.tsx, apps/official-journal-web/src/screens/CasePublishingOverview.tsx, libs/shared/dto/src/lib/cases/get-cases-query.dto.ts, libs/shared/dto/src/lib/cases/post-publish-body.dto.ts, libs/shared/modules/src/case/case.module.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/helpers/mappers/case/case-parameters.mapper.ts, libs/shared/modules/src/journal/journal.service.ts, libs/shared/modules/src/lib/utils.ts
- publish cases
- ui bug fixes
=> fix(api): Publish cases and ui fixes

apps/official-journal-web/src/components/comments/Comments.tsx, apps/official-journal-web/src/lib/constants.ts, apps/official-journal-web/src/lib/utils.tsx, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/comment/comment.service.ts, libs/shared/modules/src/utility/utility.service.interface.ts, libs/shared/modules/src/utility/utility.service.ts
Fixing comment section. Now formats all available status and cases.
Commenting works now.
=> fix(comments): Update comments in flow

libs/shared/modules/src/helpers/migrations/advert/advert-migrate.ts
Remove "fyrir" test in title. this should come from subject.
REGLUGERÐ um ...
AUGLÝSING um ...
GJALDSKRÁ fyrir ...
=> fix: adverts can't have fixed text in title

apps/official-journal-api/migrations/initial-migrations-official-journal.js, libs/shared/decorators/src/lib/log-and-handle.decorator.ts, libs/shared/decorators/src/lib/transactional.decorator.ts, libs/shared/modules/src/application/application.module.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/case/case.service.interface.ts, libs/shared/modules/src/case/case.service.spec.ts, libs/shared/modules/src/case/case.service.ts
- Fixed create case method (involved party bug)
- Added documentation to post application method in application service
- Added missing table case channels to drop query
=> fix(api): Fixed create case method

apps/official-journal-api/src/app/journal/journal.controller.ts
- Updated journal controller to use the route decorator.
=> fix(api): Journal controller update swagger documentation

README.md, libs/shared/decorators/src/lib/handle-api-exception.decorator.ts, libs/shared/decorators/src/lib/log-and-handle.decorator.ts, libs/shared/decorators/src/lib/utils.ts, libs/shared/modules/src/utility/utility.service.ts
- Added async/await modifier to the log and handle decorator
=> fix(api): Fixed error handling on the server

libs/shared/modules/src/pdf/pdf.controller.ts, libs/shared/modules/src/pdf/pdf.service.ts, libs/shared/modules/src/utility/utility.service.interface.ts, libs/shared/modules/src/utility/utility.service.ts
Making pdf generation possible for application that have not yet been submitted since there is no case to look for.
=> feat(api): PDF for applications

libs/shared/modules/src/application/application.service.ts
- Cases now get created when applications are submitted for the first time
=> fix(api): postApplication create case fix

apps/official-journal-api/src/app/journal/journal.controller.spec.ts, apps/official-journal-api/src/app/journal/journal.controller.ts, apps/official-journal-api/src/app/journal/journal.module.ts
- public api can now access cases in progress
=> feat(api): Journal api cases in progress

apps/official-journal-application-api/src/app/application/application.controller.ts, libs/shared/pipelines/src/lib/file-type.pipe.ts
- Fixed the swagger documentation for uploadAttachments route
- Added max files to the route aswell.
=> fix(api): application api swagger docs

apps/official-journal-application-api/src/app/application/application.controller.ts
Added `applications` to the key
=> fix(s3): Fixed upload key for application attachments

README.md, apps/official-journal-application-api/src/app/application/application.controller.ts, libs/shared/modules/src/application/application.service.interface.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/attachments/attachment.service.interface.ts, libs/shared/modules/src/attachments/attachment.service.ts, libs/shared/modules/src/s3/s3.service.interface.ts, libs/shared/modules/src/s3/s3.service.ts
- Get object method that allows opening files from web project
- Added get attachments by type to allow us to fetch specific type of attachments.
=> feat(api): S3 GetObject signed url

apps/official-journal-application-api/src/app/application/application.controller.ts, libs/shared/constants/src/lib/constants.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/utils/src/lib/serverUtils.ts
- Added a utility function that calculates price for an application
- Added UUIDValidationPipe on application controllers where needed
=> feat(api): Add calculation for application price

apps/official-journal-web/clientConfig.json
Client config accidentally erased earlier. Added back.
=> fix(web): Add clientconfig back

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-api/src/app/journal/journal.controller.ts, apps/official-journal-api/src/main.ts, libs/shared/modules/src/pdf/pdf.controller.ts
- Added UUID validation to all controllers methods that use id for parameters.
- Added exception factory to journal api
=> chore(api): Add UUID validation to all parameters

libs/shared/modules/src/comment/comment.service.ts
- Added check that handles if the call to application system api fails, we still create the comment.
=> fix(api): Add check for storing state in comments.

libs/shared/middleware/src/lib/log-request.middleware.ts
=> feat(api): Logging headers

apps/official-journal-application-api/src/app/app.module.ts
Added health route to exclude route for auth middleware
=> fix(api): Remove auth from health check

apps/official-journal-application-api/src/app/app.module.ts
Added global prefix to the health check route
=> fix(api): Add prefix to health path

apps/official-journal-application-api/src/app/app.module.ts
=> fix(api): Remove health check from auth middleware

libs/shared/modules/src/signature/signature.service.ts
- Removed unnecessary check (and wrong)
=> fix(api): Signature service

apps/official-journal-admin-api/src/app/statistics/statistics.controller.ts, apps/official-journal-admin-api/src/app/statistics/statistics.service.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/case/case.utils.ts, libs/shared/modules/src/case/mappers/case-parameters.mapper.ts
- fixed wrong property used extracting the case status title in the counterResults method
- removed unnecessary case status lookups when they are passed in as query parameters.
=> fix(api): Fixed counter results and optimised case fetching

apps/official-journal-application-api/src/app/application/application.controller.ts, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/lib/utils.tsx, apps/official-journal-web/src/pages/heildaryfirlit/index.tsx, apps/official-journal-web/src/pages/index.tsx, apps/official-journal-web/src/pages/ritstjorn/[...uid].tsx, apps/official-journal-web/src/pages/ritstjorn/index.tsx, apps/official-journal-web/src/pages/utgafa/index.tsx, libs/shared/modules/src/application-user/application-user.service.ts, libs/shared/modules/src/guards/application-auth.guard.ts
Removed undefined from getServerSideProps and fixed auth guard on application api and improved logging.
=> fix(api): Application API auth and no undefined in getServerSideProps

apps/official-journal-api/migrations/initial-migrations-official-journal.js, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/advert-display/AdvertDisplay.tsx, apps/official-journal-web/src/components/comments/Comments.css.ts, apps/official-journal-web/src/components/comments/Comments.tsx, apps/official-journal-web/src/components/editor/Editor.css.ts, apps/official-journal-web/src/components/editor/Editor.tsx, apps/official-journal-web/src/components/form-steps/StepInnsending.tsx, apps/official-journal-web/src/components/form-steps/StepTilbuid.tsx, apps/official-journal-web/src/components/form-steps/StepYfirlestur.tsx, apps/official-journal-web/src/components/header/ControlPanel.tsx, apps/official-journal-web/src/components/tables/CaseTableOverview.tsx, apps/official-journal-web/src/components/tables/messages.ts, apps/official-journal-web/src/lib/constants.ts, apps/official-journal-web/src/lib/utils.tsx, apps/official-journal-web/src/pages/api/cases/[id]/updateStatus.ts, libs/shared/dto/src/lib/cases/case.dto.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/case/migrations/case.migrate.ts, libs/shared/modules/src/case/models/case-status.model.ts, libs/shared/modules/src/case/models/case.model.ts, libs/shared/modules/src/case/services/update/case-update.service.ts, libs/shared/modules/src/guards/application-auth.guard.ts, libs/shared/utils/src/lib/serverUtils.ts
Mostly UI changes and some API logic updated.
- Added missing column in case table.
- Added toggle for sorting comments
- Fixed update to next status method to not go further then ready for publication
- Fixed fast track calculations
- And some UI updated / improvements.
=> fix(web): Fixed bugs found during testing

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-application-api/src/app/application/application.controller.ts, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/advert-display/AdvertDisplay.tsx, apps/official-journal-web/src/components/form-steps/StepInnsending.tsx, apps/official-journal-web/src/components/form-steps/StepTilbuid.tsx, apps/official-journal-web/src/components/form-steps/StepYfirlestur.tsx, apps/official-journal-web/src/pages/api/cases/[id]/updateType.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/case/services/create/case-create.service.ts, libs/shared/modules/src/case/services/update/case-update.service.ts, libs/shared/modules/src/comment/relations/index.ts
- Admins can now updated the submitted advert html
- Updating advert type now updated correctly
- Fixed include in comments so now comments should appear in the application system.
=> fix(web): Fix updated bugs

apps/official-journal-application-api/src/app/application/application.controller.ts
Syntax error in application controller `flase` -> `false`
=> fix(api): Fixed syntax error

libs/shared/dto/src/lib/adverts/get-adverts-query.dto.ts, libs/shared/modules/src/journal/journal.service.ts
- Added date filtering for publication date
- Fixed wrong types on date parameters
=> fix(api): Journa adverts date searching

libs/shared/modules/src/journal/journal.service.ts
Fixed bug where ordering was incorrect.
=> fix(api): Fixed ordering on journal api

apps/official-journal-api/src/app/journal/journal.controller.ts, apps/official-journal-web/src/lib/utils.tsx, libs/shared/dto/src/lib/attachments/application-case.dto.ts
Fixex import to reference the file directly instead of the directory, fixing the webpack bundle of the web project.
=> fix(web): Fix web api routes 

libs/shared/constants/src/lib/constants.ts, libs/shared/dto/src/lib/application/application-advert.ts, libs/shared/modules/src/pdf/pdf-advert-template.ts, libs/shared/modules/src/pdf/pdf.service.ts, libs/shared/modules/src/pdf/puppetBrowser.ts, libs/shared/utils/src/lib/serverUtils.ts
- Implemented retry functionality for pdf service
- added disable gpu flag for docker image fix
- moved the browser to singleton.
=> fix(api): Pdf service

apps/official-journal-admin-api/Dockerfile, apps/official-journal-api/Dockerfile, apps/official-journal-application-api/Dockerfile
Downgraded docker file node image down to 20. Since some of our dependencies require <21
=> fix(docker): Downgrade node version

apps/official-journal-web/src/components/attachments/Attachments.tsx, apps/official-journal-web/src/components/attachments/messages.ts, apps/official-journal-web/src/components/form-footer/FixStep.tsx, apps/official-journal-web/src/components/form-footer/FormFooter.tsx, apps/official-journal-web/src/components/form-footer/NextStep.tsx, apps/official-journal-web/src/components/form-footer/PrevStep.tsx, apps/official-journal-web/src/lib/messages/caseSingle.tsx, apps/official-journal-web/src/pages/ritstjorn/[...uid].tsx, libs/shared/modules/src/case/case.service.ts
- Form footer UI refactor / improvements - code split into components.
- Case Service publish advert now creates the advert with the signature html included
=> fix(web): Form footer

libs/shared/constants/src/lib/constants.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/case/services/update/case-update.service.ts, libs/shared/modules/src/utility/utility.service.interface.ts, libs/shared/modules/src/utility/utility.service.ts
- Now cases wont be rejected when admin makes an external comment to the application user
=> fix(api): Added correct status to reject

libs/shared/modules/src/pdf/pdf-advert-template.ts, libs/shared/modules/src/pdf/pdf.css.ts, libs/shared/modules/src/pdf/pdf.service.ts
Fixed issues where classes where not closed with quotes, and css import was not working as expected.
=> fix(api): Pdf css

libs/shared/modules/src/pdf/pdf-advert-template.ts, libs/shared/modules/src/pdf/pdf.css.ts, libs/shared/modules/src/pdf/pdf.service.ts
Added cleanup function to the html content
=> fix(api): PDF add cleanup method on html content

libs/shared/modules/src/case/case.module.ts, libs/shared/modules/src/case/case.service.spec.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/journal/journal.service.ts, libs/shared/modules/src/pdf/pdf.service.ts, libs/shared/modules/src/s3/s3.service.interface.ts, libs/shared/modules/src/s3/s3.service.ts, libs/shared/utils/src/lib/serverUtils.ts
- PDF's are now generated for the adverts when cases are published.
- Updated the publish cases method to only publish one case at a time because the iterations depend on the previous one.
=> feat(api): Advert PDF

libs/shared/modules/src/case/models/case-addition.model.ts, libs/shared/modules/src/case/services/create/case-create.service.interface.ts, libs/shared/modules/src/case/services/create/case-create.service.ts
- Moved case addition logic to its own method
- Fixed case addition model where type filed was mapped to title field
=> fix(api): Case addition

apps/official-journal-admin-api/src/app/case/case.controller.ts
hide roles in dmr auth for testing
=> hide roles in dmr auth

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-web/src/pages/api/cases/categories.ts
=> Categories guard logging test

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-web/src/pages/api/auth/[...nextauth].ts, apps/official-journal-web/src/pages/api/cases/categories.ts
add guard to single case add max age to session
=> add guard to single case add max age to session

apps/official-journal-web/src/components/tooltips/messages.ts, apps/official-journal-web/src/i18n/strings/is-compiled.json, apps/official-journal-web/src/i18n/strings/is.json
fixing typo 
Harðbirting 🚫 
Hraðbirting 🌷
=> Update hraðbirting typos

apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/form-steps/StepYfirlestur.tsx, apps/official-journal-web/src/components/original-compare/OriginalCompare.css.ts, apps/official-journal-web/src/components/original-compare/OriginalCompare.tsx, libs/shared/dto/src/lib/case-comments/case-comment.dto.ts, libs/shared/modules/src/comment/comment.service.ts, libs/shared/modules/src/comment/migrations/case-comment.migrate.ts
Add diff compare to yfirlestur,
- press a button
- drawer appears
- diff appears
- original appears
- toggle between diff and original.
=> Add diff compare to yfirlestur

apps/official-journal-web/src/components/editor-message/EditorMessageDisplay.tsx, apps/official-journal-web/src/components/editor-message/messages.ts, apps/official-journal-web/src/pages/ritstjorn/[...uid].tsx
Add editor message display in the ritstjorn flow
=> Add editor message display

apps/official-journal-web/src/components/comments/Comments.tsx, apps/official-journal-web/src/components/comments/messages.ts
Add button to hide comments.
Looks like a huge change, but just wrapped comments with animate height 🤷 
https://github.com/user-attachments/assets/61738bd4-40af-4f91-9e5d-6826b01975aa
=> hide comments btn

libs/shared/modules/src/application/application.module.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/signature/signature.service.interface.ts, libs/shared/utils/src/lib/serverUtils.ts
Update signature in case when signature is updated in application.
=> Update application, updates signature in case

apps/official-journal-web/src/components/access-denied/AccessDenied.tsx, apps/official-journal-web/src/pages/_error.tsx
Add access denied page when next-auth returns access denied parameter.
https://next-auth.js.org/configuration/pages#error-page
=> Access denied page

apps/official-journal-application-api/src/app/application/application.controller.ts, libs/shared/modules/src/application-user/application-user.service.interface.ts, libs/shared/modules/src/application-user/application-user.service.ts, libs/shared/modules/src/guards/application-auth.guard.ts
Fixed application auth guard not allowing application users to communicate with the api
=> fix(application-api): Application auth guard

apps/official-journal-web/next-auth.d.ts, apps/official-journal-web/src/components/header/Header.tsx, apps/official-journal-web/src/pages/api/auth/[...nextauth].ts
Invalidate session and check on frontend, then logout.
=> Invalidate session and check on frontend

apps/official-journal-web/next.config.js, apps/official-journal-web/src/components/header/ControlPanel.tsx, apps/official-journal-web/src/pages/_app.tsx
testing:
https://github.com/47ng/nuqs/blob/next/packages/docs/content/docs/troubleshooting.mdx#client-components-need-to-be-wrapped-in-a-suspense-boundary
=> layout test

apps/official-journal-web/src/components/banner/Banner.tsx, apps/official-journal-web/src/layout/Layout.tsx
- Prevent banner from being rendered on the server
=> fix(web): Dynamically import banner

apps/official-journal-application-api/src/app/application/application.controller.ts, libs/shared/dto/src/lib/adverts/get-advert-template-response.dto.ts, libs/shared/modules/src/application/application.service.interface.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/utils/src/lib/serverUtils.ts
=> chore(template): Update template response

apps/official-journal-web/src/components/banner-card/BannerCard.css.ts, apps/official-journal-web/src/components/banner-card/BannerCard.tsx, apps/official-journal-web/src/components/banner-card/BannerCardList.tsx, apps/official-journal-web/src/components/header/ControlPanel.css.ts, apps/official-journal-web/src/components/header/ControlPanel.tsx, apps/official-journal-web/src/components/header/Header.css.ts, apps/official-journal-web/src/components/header/Header.tsx, apps/official-journal-web/src/components/statistics/PieCharts.tsx, apps/official-journal-web/src/lib/utils.tsx
- Updated the control panel navigation menu
- Updated the banner cards to allow wrapping at x inline size
- Added fixed decimal points for numbers with many decimal points
=> fix(web): Frontpage fixes from design review

apps/official-journal-web/src/components/original-compare/OriginalCompare.tsx
- Added check for html when indexing array
=> fix(web): add check for html in case processing

apps/official-journal-web/src/components/case-update-fields/CaseCorrectionField.tsx, apps/official-journal-web/src/components/case-update-fields/CaseFields.tsx, apps/official-journal-web/src/components/corrections/AddCorrection.tsx, apps/official-journal-web/src/components/corrections/Corrections.tsx, apps/official-journal-web/src/components/form/FormShell.tsx, apps/official-journal-web/src/context/caseContext.tsx, apps/official-journal-web/src/pages/api/cases/[id]/reject.ts
- Added corrections into the case processing screen
- Lifted up local states to the case context for easier data manipulation
=> feat(web): Add correction to case processing

apps/official-journal-web/src/components/comments/CommentList.tsx
- Added spacing around the alert box in comment section
=> fix(web): Add spacing when no comments are present

apps/official-journal-web/src/pages/api/cases/publish.ts
- Fixed publish api route which was transforming the array of ids into comma seperated string
=> fix(web): Fix publish cases api route

apps/regulations-api-server/src/routes/health.ts, apps/regulations-api-server/src/server.ts
Add health endpoint for regulation api
=> regulations(api-server): Add health endpoint for regulation api

apps/official-journal-web/src/pages/api/cases/[id]/updateAdvertWithCorrection.ts
=> ojoi(corrections): move client in correction endpoint

apps/official-journal-web/src/pages/api/cases/[id]/updateAdvertWithCorrection.ts
Add auth to api route. fixing 403.
=> fix(corrections): Fix auth

apps/official-journal-web/src/components/header/ControlPanel.tsx, apps/official-journal-web/src/components/header/Header.tsx, apps/official-journal-web/src/components/page-loader/page-loader.tsx, apps/official-journal-web/src/layout/Layout.tsx, apps/official-journal-web/src/pages/innskraning.tsx
page transition similar to island.is to match style.
Add loader to login.
=> Add page transition loader

libs/shared/modules/src/journal/journal.service.ts, libs/shared/utils/src/lib/constants.ts
Fix template
From 1 to 2 instead of 1 to 3.
Fix similar weight
Involved party is the vip.
=> Fix template. Fix similar weight OJOI service.

apps/official-journal-web/src/components/case-update-fields/CaseFields.tsx, libs/shared/dto/src/lib/comments/comment.dto.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/comment/v2/comment.service.ts, libs/shared/modules/src/utility/utility.service.ts
- Comments are now working properly
- Signature is now included in the case migrate
=> fix(api): Fixed outdated code that handles interaction for application

libs/shared/dto/src/lib/application/application-signature.dto.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/case/services/create/case-create.service.ts, libs/shared/modules/src/pdf/pdf.service.ts, libs/shared/utils/src/lib/serverUtils.ts
- Updated the application dto to match that from the application system
=> chore(api): Updated application dto

libs/shared/dto/src/lib/application/application-answers.dto.ts, libs/shared/modules/src/case/services/create/case-create.service.ts, libs/shared/modules/src/pdf/pdf.service.ts
Replaced `signatures` -> `signature`
=> fix(api): Fix property typo name

libs/shared/modules/src/journal/journal.service.ts
- Filtering after publication number now possible
=> feat(api): Advert search

libs/shared/dto/src/lib/application/application-misc.ts, libs/shared/modules/src/case/services/create/case-create.service.ts
- Signature type now defaulted to regular
=> fix(api): Defaulting signature type

apps/official-journal-web/src/lib/token-service/index.ts, apps/official-journal-web/src/pages/api/auth/[...nextauth].ts
fix response for response token after update.
=> fix(ojoi): refresh token response

libs/shared/dto/src/lib/application/application-answers.dto.ts, libs/shared/modules/src/case/services/create/case-create.service.ts, libs/shared/modules/src/pdf/pdf.service.ts
- Added better checking for signature type if not set in application
=> fix(api): Signature type checking

apps/official-journal-application-api/src/app/application/application.controller.ts, apps/official-journal-web/clientConfig.json, libs/shared/dto/src/lib/application/application-signature.dto.ts, libs/shared/dto/src/lib/pdf/get-pdf-response.dto.ts, libs/shared/modules/src/pdf/pdf.controller.ts, libs/shared/utils/src/lib/serverUtils.ts
Fix response for application pdf
=> fix(ojoi): Fix response for application pdf

apps/official-journal-admin-api/src/app/app.module.ts, apps/official-journal-admin-api/src/app/case/case.controller.ts, libs/shared/interceptors/.eslintrc.json, libs/shared/interceptors/README.md, libs/shared/interceptors/jest.config.ts, libs/shared/interceptors/project.json, libs/shared/interceptors/src/index.ts, libs/shared/interceptors/src/lib/index.ts, libs/shared/interceptors/src/lib/logging.interceptor.ts, libs/shared/interceptors/tsconfig.json, libs/shared/interceptors/tsconfig.lib.json, libs/shared/interceptors/tsconfig.spec.json, tsconfig.base.json
- New logging interceptor globally set on the admin api app module that applies it to all routes.
=> feat(api): Logging interceptor

apps/regulations-api/project.json, apps/regulations-api/src/db/Regulation.ts, apps/regulations-api/src/db/RegulationPdf.ts, apps/regulations-api/src/server.ts, apps/regulations-api/src/utils/server-utils.ts
Add static path fix for regulation api
=> fix(regulations-api): Static paths

apps/official-journal-web/src/pages/api/cases/[id]/attachments/[aid]/index.ts, apps/official-journal-web/src/pages/api/cases/[id]/comments/[cid]/delete.ts, apps/official-journal-web/src/pages/api/cases/[id]/reject.ts, apps/official-journal-web/src/pages/api/cases/[id]/unpublish.ts, apps/official-journal-web/src/pages/api/cases/[id]/updateFasttrack.ts, apps/official-journal-web/src/pages/api/cases/communicationStatuses.ts, apps/official-journal-web/src/pages/api/cases/departments.ts, apps/official-journal-web/src/pages/api/cases/index.ts, apps/official-journal-web/src/pages/api/cases/nextPublicationNumber.ts, apps/official-journal-web/src/pages/api/cases/publish.ts, apps/official-journal-web/src/pages/api/cases/tags.ts, apps/official-journal-web/src/pages/api/cases/withDepartmentCount.ts, apps/official-journal-web/src/pages/api/cases/withPublicationNumber.ts, apps/official-journal-web/src/pages/api/cases/withStatusCount.ts, apps/official-journal-web/src/pages/api/categories/[id].ts, apps/official-journal-web/src/pages/api/categories/index.ts, apps/official-journal-web/src/pages/api/mainCategories/[id]/categories/[cid].ts, apps/official-journal-web/src/pages/api/mainCategories/[id]/index.ts, apps/official-journal-web/src/pages/api/mainCategories/index.ts, apps/official-journal-web/src/pages/api/mainTypes/[id].ts, apps/official-journal-web/src/pages/api/mainTypes/index.ts, apps/official-journal-web/src/pages/api/types/[id].ts, apps/official-journal-web/src/pages/api/types/index.ts
Added missing auth middlewares where needed in api routes.
=> fix(web): Add auth header

apps/regulations-api/src/utils/sequelize.ts, package.json, yarn.lock
=> fix(regulations-api): Update pg

apps/official-journal-web/src/components/case-update-fields/CaseFields.tsx, apps/official-journal-web/src/components/case-update-fields/CommunicationChannelsField.tsx
- Communication channels are now visible for admins
=> feat(ojoi): UI for communication channels

apps/official-journal-web/clientConfig.json, libs/shared/dto/src/lib/users/user.dto.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/case/models/case-history.model.ts, libs/shared/modules/src/user/migration/user.migrate.ts
- Replaced old admin userid with user id
- Fixed Date type in user dto so that we can serialize to json
- Re added approve application when case is published
=> fix(ojoi): Case history

apps/official-journal-web/next-auth.d.ts, apps/official-journal-web/src/components/header/ControlPanel.tsx, apps/official-journal-web/src/middleware.ts, apps/official-journal-web/src/pages/_app.tsx, apps/official-journal-web/src/pages/tegundir/index.tsx, libs/shared/modules/src/guards/involved-party.guard.ts, libs/shared/modules/src/user/user.service.ts
- New middleware that redirect Editors to the user management page
- Small fix for user creation
=> fix(ojoi): Web middleware

apps/legal-gazette-web/next-auth.d.ts, apps/official-journal-web/next-auth.d.ts, apps/official-journal-web/src/lib/constants.ts, apps/official-journal-web/src/lib/identityProvider.ts, apps/official-journal-web/src/pages/api/auth/[...nextauth].ts, apps/official-journal-web/src/pages/notendur/index.tsx, apps/official-journal-web/src/pages/ritstjorn/[...uid].tsx, apps/official-journal-web/src/pages/utgafa/stadfesting.tsx, apps/official-journal-web/src/pages/yfirflokkar/index.tsx
us id token instead of accesstoken for nationalid.
=> fix(ojoi): Update ids user national id handling

libs/shared/modules/src/journal/journal.service.ts
- Added check if both date to and from are passed and only return adverts between those dates
=> fix(ojoi): Date filtering on adverts

libs/shared/modules/src/application/migrations/application-case.migration.ts
- Added addition html to the html response for application case
=> feat(ojoi): Add addition html to application case

apps/official-journal-web/src/components/attachments/Attachments.tsx, apps/official-journal-web/src/hooks/useAttachments.ts, apps/official-journal-web/src/pages/api/cases/[id]/attachments/[aid]/index.ts, libs/shared/modules/src/attachments/attachment.service.ts
=> fix(ojoi): Attachment wont open up

apps/official-journal-web/src/components/header/Header.tsx, apps/official-journal-web/src/lib/api/createEnhancedFetch.ts, apps/official-journal-web/src/lib/api/handleAuthErrors.ts
=> chore(ojoi): Handle logout on auth errors

apps/official-journal-web/src/middleware.ts
Remove redundant check for token in middleware
=> fix(ojoi): Remove redundant check

apps/official-journal-web/src/hooks/api/get/useCommunicationChannels.ts, apps/official-journal-web/src/hooks/useAttachments.ts
After recent update, these changes were missing.
=> fix(ojoi): Use accesstoken

apps/official-journal-web/src/i18n/strings/is-compiled.json, apps/official-journal-web/src/i18n/strings/is.json, apps/official-journal-web/src/pages/index.tsx, apps/official-journal-web/src/pages/utgafa/stadfesting.tsx
Remove lorem ipsum. Add real text.
=> fix(ojoi): Add missing strings

libs/shared/modules/src/auth/auth.service.ts, libs/shared/modules/src/journal/journal.service.ts
Add corrections to advert, add xroad error log
=> fix(ojoi): Add corrections to advert, add xroad error log

apps/official-journal-api/migrations/m-2025330301-add-legacy-corrections.js, apps/official-journal-web/clientConfig.json, libs/shared/dto/src/lib/adverts/advert-correction.dto.ts, libs/shared/modules/src/journal/migrations/advert-correction.migrate.ts, libs/shared/modules/src/journal/models/advert-correction.model.ts
=> feat(ojoi): legacy dates in corrections

apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/tables/UsersTable.tsx, apps/official-journal-web/src/components/users/UserDetailed.tsx, libs/shared/dto/src/lib/users/user.dto.ts, libs/shared/modules/src/user/user.service.ts
=> feat(ojoi): Editor edit roles

apps/official-journal-web/src/pages/ritstjorn/[...uid].tsx
=> fix(ojoi): Max page size

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/attachments/Attachments.tsx, apps/official-journal-web/src/components/case-update-fields/AdvertFields.css.ts, apps/official-journal-web/src/components/case-update-fields/AdvertFields.tsx, apps/official-journal-web/src/hooks/useAttachments.ts, apps/official-journal-web/src/lib/utils.tsx, libs/shared/dto/src/lib/s3/presigned-url-response.dto.ts, libs/shared/modules/src/case/case.service.interface.ts, libs/shared/modules/src/case/case.service.ts
* Fix re-upload
* Fix image hanlding in editor
* Add upload attachment
* Fix css
=> fix(ojoi): Presigned admin fixes

apps/official-journal-web/src/components/attachments/Attachments.tsx
=> fix(ojoi): Upload even if no attachment

libs/shared/modules/src/utility/utility.service.ts
Lookup util signature addition
=> fix(ojoi): Lookup util signature addition

libs/shared/modules/src/pdf/pdf-advert-template.ts, libs/shared/modules/src/pdf/pdf.css.ts, libs/shared/modules/src/pdf/pdf.service.ts
Hide signature in application on PDF, show in case PDF
=> fix(ojoi): Hide signature draft, show in case

libs/shared/modules/src/utility/utility.service.ts
=> fix(ojoi): Use year for publishdate

libs/shared/modules/src/pdf/pdf-advert-template.ts, libs/shared/modules/src/pdf/pdf.css.ts, libs/shared/modules/src/pdf/pdf.service.ts, libs/shared/modules/src/signature/utils.ts
=> fix(ojoi): Pdf styling for cases

libs/shared/modules/src/pdf/pdf.css.ts, libs/shared/modules/src/pdf/pdf.service.ts, libs/shared/modules/src/signature/utils.ts
=> fix(ojoi): Extra styling for pdf

libs/shared/modules/src/signature/utils.ts
=> fix(ojoi): Signature inline style

apps/official-journal-web/src/context/caseContext.tsx, apps/official-journal-web/src/lib/utils.tsx, libs/shared/modules/src/advert-type/models/advert-main-type.model.ts, libs/shared/modules/src/advert-type/models/advert-type.model.ts, libs/shared/modules/src/advert-type/models/stringUtils.ts, scripts/run-xroad-proxy.sh
=> fix(ojoi): Advert type and main advert type capitalized

apps/official-journal-web/src/components/price/calculator.tsx
=> fix(ojoi): Update price init fetch

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-api/migrations/m-d20250410-add-order-to-additions.js, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/case-update-fields/AppendixFields.tsx, apps/official-journal-web/src/components/case-update-fields/CaseFields.tsx, apps/official-journal-web/src/components/price/calculator.tsx, apps/official-journal-web/src/pages/_app.tsx, libs/shared/dto/src/lib/cases/case-addition.dto.ts, libs/shared/dto/src/lib/cases/update-advert-html-body.dto.ts, libs/shared/modules/src/case/case.service.interface.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/case/migrations/case-addition.migrate.ts, libs/shared/modules/src/case/models/case-addition.model.ts, libs/shared/modules/src/case/models/case-additions.model.ts, libs/shared/modules/src/case/relations/index.ts, libs/shared/modules/src/case/services/create/case-create.service.interface.ts, libs/shared/modules/src/case/services/create/case-create.service.ts, libs/shared/modules/src/case/services/update/case-update.service.interface.ts, libs/shared/modules/src/case/services/update/case-update.service.ts, libs/shared/modules/src/utility/utility.service.ts
=> chore(ojoi): Add appendix for editors

libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/pdf/pdf.service.ts
Update document pdf name for path
=> fix(ojoi): Update document pdf name for path

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/price/StatusBox.tsx, apps/official-journal-web/src/components/price/calculator.tsx, apps/official-journal-web/src/pages/_app.tsx, libs/shared/api-client/src/lib/createClient.ts
calculator status and refresh client
=> fix(ojoi): Calculator status and refresh client

apps/official-journal-web/src/components/price/calculator.tsx
=> fix(ojoi): Can re send tbr on access

libs/shared/modules/src/pdf/pdf.service.ts, libs/shared/utils/src/lib/serverUtils.ts
Format and normalize dates in pdf
=> fix(ojoi): Format and normalize dates in pdf

libs/shared/modules/src/pdf/pdf.service.ts, libs/shared/utils/src/lib/serverUtils.ts
=> fix(ojoi): Format any date

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/tables/messages.ts, apps/official-journal-web/src/lib/constants.ts, apps/official-journal-web/src/pages/yfirskrifa-pdf/[...uid].tsx, libs/shared/dto/src/lib/cases/update-advert-html-body.dto.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/case/case.service.interface.ts, libs/shared/modules/src/case/case.service.mock.ts, libs/shared/modules/src/case/case.service.spec.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/case/models/index.ts
Option to update advert main text.
=> feat(ojoi): Update advert main text option

apps/official-journal-admin-api/src/app/case/case.controller.ts, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/tables/messages.ts, apps/official-journal-web/src/lib/constants.ts, apps/official-journal-web/src/pages/yfirskrifa-pdf/[...uid].tsx, libs/shared/dto/src/lib/cases/update-advert-html-body.dto.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/case/case.service.interface.ts, libs/shared/modules/src/case/case.service.mock.ts, libs/shared/modules/src/case/case.service.spec.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/case/models/index.ts
=> fix(ojoi): Revert Update advert main text option

apps/official-journal-application-api/src/app/application/application.controller.ts
=> fix(ojoi): Move user endpoint

apps/official-journal-api/migrations/m-d20250430-add-proposed-advert-id.js, apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/case-update-fields/CommonFields.tsx, apps/official-journal-web/src/components/case-update-fields/utils.ts, apps/official-journal-web/src/components/select/OJOIInput.tsx, libs/shared/dto/src/lib/adverts/advert.dto.ts, libs/shared/dto/src/lib/cases/case.dto.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/case/migrations/case-detailed.migrate.ts, libs/shared/modules/src/case/models/case.model.ts, libs/shared/modules/src/case/services/create/case-create.service.ts, libs/shared/modules/src/journal/journal.service.ts
=> feat(ojoi): Add proposed advert id

libs/shared/modules/src/pdf/pdf.service.ts
=> fix(ojoi): Add browser close

libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/pdf/pdf.service.ts
sluggify the filename for attachments,.
=> fix(ojoi): Slugify pdf filename

libs/shared/modules/src/pdf/pdf-advert-template.ts, libs/shared/modules/src/pdf/pdf.service.ts, libs/shared/modules/src/utility/utility.service.ts
w header
display the addition correctly.
=> fix(ojoi): Fix display for text additions in PDF

apps/legal-gazette-api/src/app/app.module.ts, apps/legal-gazette-api/src/main.ts, apps/legal-gazette-api/src/modules/application/application.controller.ts, apps/legal-gazette-api/src/modules/application/application.module.ts, apps/legal-gazette-api/src/modules/application/application.service.interface.ts, apps/legal-gazette-api/src/modules/application/application.service.ts, apps/legal-gazette-api/src/modules/application/dto/application.dto.ts, libs/legal-gazette/dto/src/lib/api-error.dto.ts, libs/shared/filters/src/lib/http-exception.filter.ts, package.json
Application module which has a endpoint that accepts applications submitted from the application system.
=> feat(legal-gazette): Application module for handling submissions from the application system

libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/pdf/pdf.service.interface.ts
Fix pdf publish date
We are handling any date format in the pdf service.
No need to convert in case service anymore
=> fix(ojoi): Fix pdf publish date

apps/legal-gazette-api/src/modules/case-category/case-category.controller.ts
Fixed generated client duplicate export
=> fix(lg): Client config

apps/legal-gazette-api/src/modules/application/dto/application.dto.ts
Added property `categoryId` to submit application dto.
=> feat(api): Add category id to submit application dto

libs/shared/modules/src/pdf/pdf.service.ts
Fix indentation cutting off text
=> fix(ojoi): Indentation cutting off text

libs/shared/modules/src/journal/journal.service.ts, libs/shared/modules/src/journal/util/removeAllHtmlComments.ts
remove html comments before dirty clean
=> fix(ojoi): remove html comments before dirty clean

libs/shared/modules/src/journal/journal.service.ts
=> fix: Revert "fix: remove race"

apps/official-journal-web/src/components/advert-display/AdvertDisplay.css.ts, apps/official-journal-web/src/components/advert-display/AdvertDisplay.tsx, apps/official-journal-web/src/components/appendixes/Appendixes.tsx
Display full advert preview in advertfield.
Better understanding for editors on how case will look on external web.
=> fix(ojoi): Display full advert preview in advertfield

apps/official-journal-web/src/components/advert-display/AdvertDisplay.tsx
=> fix(ojoi): publish date for preview string

apps/legal-gazette-api/src/guards/advert-update.guard.ts, apps/legal-gazette-api/src/lib/utils.ts, apps/legal-gazette-api/src/modules/advert/advert.model.ts, apps/legal-gazette-api/src/modules/advert/advert.module.ts, apps/legal-gazette-api/src/modules/advert/controllers/advert-common.controller.ts, apps/legal-gazette-api/src/modules/advert/controllers/advert-update.controller.ts, apps/legal-gazette-api/src/modules/category/category.model.ts, apps/legal-gazette-api/src/modules/common-advert/common-advert.model.ts, apps/legal-gazette-api/src/modules/status/status.model.ts, apps/legal-gazette-api/src/services/publishing/publishing.service.ts
- Added advert update guard that checks if the advert is in the allowed status to be updated.
- Updated the publishing task to check if the advert is scheduled for today or older
=> feat(legal-gazette): Advert update validation logic

libs/shared/modules/src/aws/aws.service.ts, libs/shared/modules/src/journal/journal.service.ts
Fix pdf overwrite path on external adverts.
=> fix(ojoi): Fix pdf overwrite path on external adverts

libs/shared/dto/src/lib/adverts/get-adverts-query.dto.ts, libs/shared/modules/src/journal/journal.service.ts
Add `year` filter parameter for signature year in adverts query.
=> chore(ojoi): Filter param by year

libs/shared/dto/src/lib/adverts/get-adverts-query.dto.ts
=> fix(ojoi): Fix spelling

libs/shared/modules/src/signature/signature.module.ts, libs/shared/modules/src/signature/signature.service.ts
* Update case year and signature date based on signature Create, Update, Delete.
=> fix(ojoi): Update case year and signature date by signature

apps/official-journal-api/migrations/m-d20250707-add-tsv-column-to-advert.js, libs/shared/modules/src/journal/journal.service.ts
=> feat(ojoi): Search by text

libs/shared/dto/src/lib/attachments/application-case.dto.ts, libs/shared/modules/src/application/migrations/application-case.migration.ts
Application expected publish date to application case endpoint
=> fix(ojoi): Application expected publishing date

apps/official-journal-api/migrations/m-d20250709-add-legacy-pdf-column.js
Add legacy pdf column for redirect mapping
=> fix(ojoi): Add legacy pdf column

apps/official-journal-api/src/app/journal/journal.controller.ts, libs/shared/modules/src/journal/journal.service.interface.ts, libs/shared/modules/src/journal/journal.service.mock.ts, libs/shared/modules/src/journal/journal.service.ts, libs/shared/modules/src/journal/models/advert.model.ts
=> fix(ojoi): Handle legacy pdf redirects

libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/pdf/pdf-advert-template.ts, libs/shared/modules/src/pdf/pdf.service.interface.ts, libs/shared/modules/src/pdf/pdf.service.ts
Corrections.
Add disclaimer to PDF.
Update body text on advert when corrected.
=> fix(ojoi): Corrections pdf and body update

apps/official-journal-api/src/app/app.module.ts, libs/shared/middleware/src/lib/log-request.middleware.ts, tsconfig.base.json
Allows us to see the full url on all request for debugging purposes.
=> feat(ojoi): Add logging middleware

libs/shared/modules/src/pdf/pdf.css.ts
=> fix: update display

apps/official-journal-web/clientConfig.json, apps/official-journal-web/src/components/price/calculator.tsx, apps/official-journal-web/src/components/tables/CaseTable.css.ts, apps/official-journal-web/src/components/tables/CaseTableOverview.tsx, apps/official-journal-web/src/components/tables/InvoiceCol.tsx, apps/official-journal-web/src/components/tables/messages.ts, apps/official-journal-web/src/hooks/api/get/useGetPaymentStatus.ts, libs/shared/dto/src/lib/cases/case.dto.ts, libs/shared/modules/src/case/case.service.ts, libs/shared/modules/src/case/mappers/case-parameters.mapper.ts, libs/shared/modules/src/case/migrations/case.migrate.ts, libs/shared/modules/src/price/price.service.interface.ts, libs/shared/modules/src/price/price.service.ts
Better oversight of finance data.
Improved search parameter.
=> fix(ojoi): Update heildaryfirlit, add to search, add tbr info

apps/legal-gazette-api/db/migrations/inital-migration-legal-gazette.js, apps/legal-gazette-api/src/app/app.module.ts, apps/legal-gazette-api/src/lib/constants.ts, apps/legal-gazette-api/src/modules/advert-publications/advert-publications.model.ts, apps/legal-gazette-api/src/modules/advert/advert.model.ts, libs/shared/filters/src/lib/global-exception.filter.ts, libs/shared/models/base/src/lib/base.model.ts
- New table that will store all publications of an advert
- Extended the base model class, added findOrThrow static and instance methods
=> feat(legal-gazette): Advert publications

package.json, yarn.lock
=> chore: update nextjs to fix middleware vulnerability

libs/shared/modules/src/guards/role-guard.ts
Use involved party national id for role
=> fix(ojoi): Use involved party national id for role

apps/official-journal-application-api/src/app/application/application.controller.ts, apps/official-journal-application-api/src/app/guards/party.guard.ts, libs/shared/modules/src/guards/role-guard.ts, libs/shared/modules/src/user/user.service.interface.ts, libs/shared/modules/src/user/user.service.ts
Add party guard.
Clean up role guard.
=> fix(ojoi): Add party guard

libs/shared/modules/src/application/application.service.interface.ts, libs/shared/modules/src/application/application.service.ts, libs/shared/modules/src/comment/v2/comment.service.interface.ts, libs/shared/modules/src/comment/v2/comment.service.ts, libs/shared/modules/src/comment/v2/migrations/comment.migrate.ts
Use involvedParty when no userCreator
=> fix(ojoi): Update migrate comments

libs/shared/modules/src/pdf/pdf.css.ts
* Add spacing on ol > li
* Fix 1 typo
=> fix(ojoi): pdf styles

apps/official-journal-web/src/components/comments/AddCommentTab.tsx, apps/official-journal-web/src/components/form/FormShell.tsx, apps/official-journal-web/src/context/caseContext.tsx, apps/official-journal-web/src/hooks/api/update/useUpdateCommunicationStatus.ts, apps/official-journal-web/src/pages/api/cases/[id]/updateCommunicationStatus.ts, libs/shared/modules/src/case/case.service.ts
Editor can update communication status
=> fix(ojoi): Editor can update communication status

apps/legal-gazette-api/src/app/app.module.ts, apps/legal-gazette-api/src/guards/machine-client.guard.ts, apps/legal-gazette-api/src/main.ts, apps/legal-gazette-api/src/modules/advert/advert.service.interface.ts, apps/legal-gazette-api/src/modules/advert/advert.service.ts, apps/legal-gazette-api/src/modules/advert/dto/advert.dto.ts, apps/legal-gazette-api/src/modules/company/company.controller.ts, apps/legal-gazette-api/src/modules/company/company.module.ts, apps/legal-gazette-api/src/modules/company/company.service.interface.ts, apps/legal-gazette-api/src/modules/company/company.service.ts, apps/legal-gazette-api/src/modules/company/dto/company.dto.ts, apps/legal-gazette-api/src/modules/company/utils.ts, apps/legal-gazette-api/src/modules/swagger/external-systems.module.ts, apps/legal-gazette-api/src/modules/tbr/tbr.service.ts, apps/legal-gazette-web/src/components/client-components/ritstjorn/fields/ContentsField.tsx
New external system module with register company endpoint.
=> feat(legal-gazette): External system modules
